development:
  adapter: postgresql
  database: macdb_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: macdb_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: macdb_production
  pool: 5
  timeout: 5000
