# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Album followed by all tracks in it

a1 = Album.create(title: "Greatest Hell's Hits", artist: "AC/DC", year: "2009", cd_number: 2, genre: "Hard Rock", tracks_num: 37, label: "Sony BMG Music Entertainment", image: "https://s.mxmcdn.net/images-storage/albums/5/3/0/4/3/8/13834035_350_350.jpg", listen: "https://www.youtube.com/watch?v=cNgPBf7eDjg")
Track.create(name: "Thunderstruck", duration: "4:54", album_id: a1.id)
Track.create(name: "Shoot To Thrill", duration: "5:19", album_id: a1.id)
Track.create(name: "Big Gun", duration: "4:22", album_id: a1.id)
Track.create(name: "Fire Your Guns", duration: "2:55", album_id: a1.id)
Track.create(name: "You Shook Me All Night Long", duration: "3:32", album_id: a1.id)
Track.create(name: "Heatseeker", duration: "3:49", album_id: a1.id)
Track.create(name: "Back In Black", duration: "4:17", album_id: a1.id)
Track.create(name: "Who Made Who", duration: "3:28", album_id: a1.id)
Track.create(name: "Rock N Roll Train", duration: "4:23", album_id: a1.id)
Track.create(name: "Hard As A Rock", duration: "4:33", album_id: a1.id)
Track.create(name: "Hells Bells", duration: "5:14", album_id: a1.id)
Track.create(name: "Moneytalks", duration: "3:47", album_id: a1.id)
Track.create(name: "What Do You Do For Money Honey", duration: "3:37", album_id: a1.id)
Track.create(name: "Are You Ready", duration: "4:12", album_id: a1.id)
Track.create(name: "Big Jack", duration: "3:59", album_id: a1.id)
Track.create(name: "Stiff Upper Lip", duration: "3:37", album_id: a1.id)
Track.create(name: "That's The Way I Wanna Rock N Roll", duration: "3:47", album_id: a1.id)
Track.create(name: "Flick Of The Switch", duration: "3:15", album_id: a1.id)
Track.create(name: "For Those About To Rock (We Salute You)", duration: "5:44", album_id: a1.id)
Track.create(name: "Highway To Hell", duration: "3:30", album_id: a1.id)
Track.create(name: "T.N.T.", duration: "3:36", album_id: a1.id)
Track.create(name: "Whole Lotta Rosie", duration: "5:25", album_id: a1.id)
Track.create(name: "The Jack", duration: "5:54", album_id: a1.id)
Track.create(name: "Girls Got Rhythm", duration: "3:25", album_id: a1.id)
Track.create(name: "Dirty Deeds Done Dirt Cheap", duration: "3:53", album_id: a1.id)
Track.create(name: "If You Want Blood (You've Got It)", duration: "4:35", album_id: a1.id)
Track.create(name: "It's A Long Way To The Top (If You Wanna Rock 'N' Roll)", duration: "5:01", album_id: a1.id)
Track.create(name: "Sin City", duration: "4:47", album_id: a1.id)
Track.create(name: "Live Wire", duration: "5:49", album_id: a1.id)
Track.create(name: "Let There Be Rock", duration: "5:49", album_id: a1.id)
Track.create(name: "High Voltage", duration: "4:08", album_id: a1.id)
Track.create(name: "Rock 'N' Roll Damnation", duration: "3:39", album_id: a1.id)
Track.create(name: "Touch Too Much", duration: "4:28", album_id: a1.id)
Track.create(name: "Jailbreak", duration: "4:42", album_id: a1.id)
Track.create(name: "Shot Down In Flames", duration: "3:24", album_id: a1.id)
Track.create(name: "Kicked In The Teeth", duration: "3:56", album_id: a1.id)
Track.create(name: "Big Balls", duration: "2:38", album_id: a1.id)

a2 = Album.create(title: "Songs In A Minor", artist: "Alicia Keys", year: "2001", cd_number: 1, genre: "Hip Hop, Funk / Soul", tracks_num: 16, label: "The Hit Factory", image: "http://images.sodahead.com/polls/000839765/polls_alicia_keys_songs_in_a_minor_1145_470262_answer_1_xlarge.jpeg", listen: "https://www.youtube.com/watch?v=0Tf5-ag28aA")
Track.create(name: "Piano &amp; I", duration: "1:51", album_id: a2.id)
Track.create(name: "Girlfriend", duration: "3:35", album_id: a2.id)
Track.create(name: "How Come You Don't Call Me", duration: "3:58", album_id: a2.id)
Track.create(name: "Fallin'", duration: "3:30", album_id: a2.id)
Track.create(name: "Troubles", duration: "4:29", album_id: a2.id)
Track.create(name: "Rock Wit U", duration: "5:37", album_id: a2.id)
Track.create(name: "A Woman's Worth", duration: "5:03", album_id: a2.id)
Track.create(name: "Jane Doe", duration: "3:48", album_id: a2.id)
Track.create(name: "Goodbye", duration: "4:21", album_id: a2.id)
Track.create(name: "The Life", duration: "5:25", album_id: a2.id)
Track.create(name: "Mr. Man", duration: "4:10", album_id: a2.id)
Track.create(name: "Never Felt This Way (Interlude)", duration: "2:01", album_id: a2.id)
Track.create(name: "Butterflyz", duration: "4:08", album_id: a2.id)
Track.create(name: "Why Do I Feel So Sad", duration: "4:26", album_id: a2.id)
Track.create(name: "Caged Bird", duration: "3:02", album_id: a2.id)
Track.create(name: "Lovin U", duration: "3:48", album_id: a2.id)

a3 = Album.create(title: "This Left Feels Right", artist: "Bon Jovi", year: "2003", cd_number: 1, genre: "Arena Rock", tracks_num: 13, label: "Island Def Jam Music Group", image: "https://artwork-cdn.7static.com/static/img/sleeveart/00/005/100/0000510083_350.jpg", listen: "https://www.youtube.com/watch?v=Fr5sm8wpjTs&list=PL7D7B601315D6A8D8")
Track.create(name: "Wanted Dead Or Alive", duration: "3:43", album_id: a3.id)
Track.create(name: "Livin' On A Prayer", duration: "3:41", album_id: a3.id)
Track.create(name: "Bad Medicine", duration: "4:27", album_id: a3.id)
Track.create(name: "It's My Life", duration: "3:42", album_id: a3.id)
Track.create(name: "Lay Your Hands On Me", duration: "4:27", album_id: a3.id)
Track.create(name: "You Give Love A Bad Name", duration: "3:29", album_id: a3.id)
Track.create(name: "Bed Of Roses", duration: "5:38", album_id: a3.id)
Track.create(name: "Everyday", duration: "3:45", album_id: a3.id)
Track.create(name: "Born To Be My Baby", duration: "5:27", album_id: a3.id)
Track.create(name: "Keep The Faith", duration: "4:12", album_id: a3.id)
Track.create(name: "I'll Be There For You", duration: "4:21", album_id: a3.id)
Track.create(name: "Always", duration: "4:19", album_id: a3.id)
Track.create(name: "The Distance (Live) Bonus Track", duration: "5:54", album_id: a3.id)

a4 = Album.create(title: "Un", artist: "Chumbawamba", year: "2004", cd_number: 1, genre: "Folk Rock, Pop Rock, Synth-pop", tracks_num: 12, label: "Mutt Records Ltd", image: "http://www.chumba.com/images/UnBIG.gif", listen: "https://www.youtube.com/watch?v=RaRIX4VOkC4")
Track.create(name: "The Wizard Of Menlo Park", duration: "3:41", album_id: a4.id)
Track.create(name: "Just Desserts", duration: "4:01", album_id: a4.id)
Track.create(name: "On eBay", duration: "3:47", album_id: a4.id)
Track.create(name: "Everything You Know Is Wrong", duration: "5:08", album_id: a4.id)
Track.create(name: "Be With You", duration: "3:27", album_id: a4.id)
Track.create(name: "When Fine Society Sits Down To Dine", duration: "5:31", album_id: a4.id)
Track.create(name: "A Man Walks Into A Bar", duration: "4:00", album_id: a4.id)
Track.create(name: "Buy Nothing Day", duration: "3:47", album_id: a4.id)
Track.create(name: "Following You", duration: "2:48", album_id: a4.id)
Track.create(name: "We Don't Want To Sing Along", duration: "3:17", album_id: a4.id)
Track.create(name: "I Did It For Alfie", duration: "2:39", album_id: a4.id)
Track.create(name: "Rebel Code", duration: "3:28", album_id: a4.id)

a5 = Album.create(title: "X&amp;Y", artist: "Coldplay", year: "2005", cd_number: 1, genre: "Acoustic, Pop Rock, Indie Rock", tracks_num: 13, label: "EMI Records Ltd.", image: "http://images.sodahead.com/polls/000126746/polls_imagen_album_coldplay_coldplay_x_26Y_0109_245821_answer_3_xlarge.jpeg", listen: "https://www.youtube.com/watch?v=zRralTaPR9I&list=PLJmUArLYkmnaAE6Rf2R5Ezx2IJqIcuVxa")
Track.create(name: "Square One", duration: "4:47", album_id: a5.id)
Track.create(name: "What If", duration: "4:57", album_id: a5.id)
Track.create(name: "White Shadows", duration: "5:28", album_id: a5.id)
Track.create(name: "Fix You", duration: "4:55", album_id: a5.id)
Track.create(name: "Talk", duration: "5:11", album_id: a5.id)
Track.create(name: "X&amp;Y", duration: "4:34", album_id: a5.id)
Track.create(name: "Speed Of Sound", duration: "4:48", album_id: a5.id)
Track.create(name: "A Message", duration: "4:45", album_id: a5.id)
Track.create(name: "Low", duration: "5:32", album_id: a5.id)
Track.create(name: "The Hardest Part", duration: "4:25", album_id: a5.id)
Track.create(name: "Swallowed In The Sea", duration: "3:59", album_id: a5.id)
Track.create(name: "Twisted Logic", duration: "5:01", album_id: a5.id)
Track.create(name: "Til Kingdom Come", duration: "4:10", album_id: a5.id)

a6 = Album.create(title: "Mylo Xyloto", artist: "Coldplay", year: "2011", cd_number: 1, genre: "Alternative Rock", tracks_num: 14, label: "EMI Records Ltd.", image: "http://cdn.acfrg.com/i/350_350_fit_ffffff__png/ACfrG/productpics_fullsize/2/216895.jpg", listen: "https://www.youtube.com/watch?v=ZRxtFTozMwI&list=PLATeyS5bPJiHjg2ifvVh4g3N2G7885SYl")
Track.create(name: "Mylo Xyloto", duration: "0:43", album_id: a6.id)
Track.create(name: "Hurts Like Heaven", duration: "4:02", album_id: a6.id)
Track.create(name: "Paradise", duration: "4:37", album_id: a6.id)
Track.create(name: "Charlie Brown", duration: "4:45", album_id: a6.id)
Track.create(name: "Us Against The World", duration: "3:59", album_id: a6.id)
Track.create(name: "M.M.I.X.", duration: "0:48", album_id: a6.id)
Track.create(name: "Every Teardrop Is A Waterfall", duration: "4:00", album_id: a6.id)
Track.create(name: "Major Minus", duration: "3:30", album_id: a6.id)
Track.create(name: "U.F.O.", duration: "2:17", album_id: a6.id)
Track.create(name: "Princess Of China", duration: "3:59", album_id: a6.id)
Track.create(name: "Up In Flames", duration: "3:13", album_id: a6.id)
Track.create(name: "A Hopeful Transmission", duration: "0:33", album_id: a6.id)
Track.create(name: "Don't Let It Break Your Heart", duration: "3:53", album_id: a6.id)
Track.create(name: "Up With The Birds", duration: "3:47", album_id: a6.id)

a7 = Album.create(title: "Fireball", artist: "Deep Purple", year: "1971", cd_number: 1, genre: "Hard Rock, Classic Rock", tracks_num: 7, label: "EMI Records Ltd.", image: "http://cdn2-b.examiner.com/sites/default/files/styles/image_content_width/hash/79/a8/1348581266_7866_fireball.jpg?itok=66YGiYJ5", listen: "https://www.youtube.com/watch?v=wJ_JvzfhodQ")
Track.create(name: "Fireball", duration: "3:22", album_id: a7.id)
Track.create(name: "No No No", duration: "6:52", album_id: a7.id)
Track.create(name: "Demon's Eye", duration: "5:16", album_id: a7.id)
Track.create(name: "Anyone's Daughter", duration: "4:40", album_id: a7.id)
Track.create(name: "The Mule", duration: "5:19", album_id: a7.id)
Track.create(name: "Fools", duration: "8:16", album_id: a7.id)
Track.create(name: "No One Came", duration: "6:24", album_id: a7.id)

a8 = Album.create(title: "Greatest Hits", artist: "Eric Clapton", year: "1996", cd_number: 1, genre: "Blues Rock, Pop Rock", tracks_num: 17, label: "Reprise Records", image: "http://getalbums.ru/uploads/posts/2009-12/1261311593_cover.jpg", listen: "https://www.youtube.com/watch?v=rDhz3qBxz1E")
Track.create(name: "I Shot The Sheriff", duration: "4:20", album_id: a8.id)
Track.create(name: "Cocaine", duration: "3:33", album_id: a8.id)
Track.create(name: "Layla (Unplugged)", duration: "4:46", album_id: a8.id)
Track.create(name: "Knocking'on Heavens Door", duration: "4:22", album_id: a8.id)
Track.create(name: "Lay Down Sally", duration: "3:47", album_id: a8.id)
Track.create(name: "I Can't Stand It", duration: "4:10", album_id: a8.id)
Track.create(name: "Tears In Heaven", duration: "4:36", album_id: a8.id)
Track.create(name: "Tearing Us Apart", duration: "4:15", album_id: a8.id)
Track.create(name: "Pretending", duration: "4:16", album_id: a8.id)
Track.create(name: "Wonderful Tonight", duration: "3:42", album_id: a8.id)
Track.create(name: "Before You Accuse Me (Take A Look At Yourself)", duration: "3:44", album_id: a8.id)
Track.create(name: "Pretty Girl", duration: "5:29", album_id: a8.id)
Track.create(name: "Promises", duration: "2:59", album_id: a8.id)
Track.create(name: "It's Probably Me", duration: "4:54", album_id: a8.id)
Track.create(name: "Behind The Mask", duration: "4:43", album_id: a8.id)
Track.create(name: "Blues Before Sunrise", duration: "2:58", album_id: a8.id)
Track.create(name: "Change The World", duration: "3:55", album_id: a8.id)

a9 = Album.create(title: "Pilgrim", artist: "Eric Clapton", year: "1998", cd_number: 1, genre: "Blues Rock", tracks_num: 14, label: "Reprise Records", image: "http://www.getmusic.com.au/store/media/catalog/product/cache/2/image/350x350/9df78eab33525d08d6e5fb8d27136e95/e/r/eric-clapton-pilgrim-1219838-1413647995.jpg", listen: "https://www.youtube.com/watch?v=pqKSnSSGh_w")
Track.create(name: "My Father's Eyes", duration: "5:24", album_id: a9.id)
Track.create(name: "River Of Tears", duration: "7:22", album_id: a9.id)
Track.create(name: "Pilgrim", duration: "5:50", album_id: a9.id)
Track.create(name: "Broken Hearted", duration: "7:52", album_id: a9.id)
Track.create(name: "One Chance", duration: "5:55", album_id: a9.id)
Track.create(name: "Circus", duration: "4:11", album_id: a9.id)
Track.create(name: "Going Down Slow", duration: "5:19", album_id: a9.id)
Track.create(name: "Fall Like Rain", duration: "3:50", album_id: a9.id)
Track.create(name: "Born In Time", duration: "4:41", album_id: a9.id)
Track.create(name: "Sick And Tired", duration: "5:43", album_id: a9.id)
Track.create(name: "Needs His Woman", duration: "3:45", album_id: a9.id)
Track.create(name: "She's Gone", duration: "4:45", album_id: a9.id)
Track.create(name: "You Were There", duration: "5:31", album_id: a9.id)
Track.create(name: "Inside Of Me", duration: "5:25", album_id: a9.id)

a10 = Album.create(title: "You've Come A Long Way, Baby", artist: "Fatboy Slim", year: "1998", cd_number: 1, genre: "Electronic", tracks_num: 11, label: "Skint Records", image: "http://i62.photobucket.com/albums/h101/rudolf55/Fatboy%20Slim/YouveComeALongWayBaby_resize.jpg", listen: "https://www.youtube.com/watch?v=ub747pprmJ8&list=PL6F3D32F3FDB19829")
Track.create(name: "Right Here, Right Now", duration: "6:28", album_id: a10.id)
Track.create(name: "The Rockafeller Skank", duration: "6:54", album_id: a10.id)
Track.create(name: "Fucking In Heaven", duration: "3:55", album_id: a10.id)
Track.create(name: "Gangster Tripping", duration: "5:20", album_id: a10.id)
Track.create(name: "Build It Up - Tear It Down", duration: "5:05", album_id: a10.id)
Track.create(name: "Kalifornia", duration: "5:53", album_id: a10.id)
Track.create(name: "Soul Surfing", duration: "4:57", album_id: a10.id)
Track.create(name: "You're Not From Brighton", duration: "5:21", album_id: a10.id)
Track.create(name: "Praise You", duration: "5:24", album_id: a10.id)
Track.create(name: "Love Island", duration: "5:18", album_id: a10.id)
Track.create(name: "Acid 8000", duration: "7:28", album_id: a10.id)

a11 = Album.create(title: "The Very Best Of Led Zeppelin - Early Days &amp; Latter Days", artist: "Led Zeppelin", year: "2002", cd_number: 2, genre: "Hard Rock, Classic Rock", tracks_num: 23, label: "Atlantic Recording Corporation", image: "http://i.imgur.com/N8DVIBX.jpg", listen: "https://www.youtube.com/watch?v=iP9xMobANJM&list=PLLpy1yrSMTp4pjSGXlDxD7DQojEb1J-FJ")
Track.create(name: "Good Times, Bad Times", duration: "2:46", album_id: a11.id)
Track.create(name: "Babe I'm Gonna Leave You", duration: "6:42", album_id: a11.id)
Track.create(name: "Dazed And Confused", duration: "6:27", album_id: a11.id)
Track.create(name: "Communication Breakdown", duration: "2:28", album_id: a11.id)
Track.create(name: "Whole Lotta Love", duration: "5:34", album_id: a11.id)
Track.create(name: "What Is And What Should Never Be", duration: "4:44", album_id: a11.id)
Track.create(name: "Immigrant Song", duration: "2:27", album_id: a11.id)
Track.create(name: "Since I've Been Loving You", duration: "7:24", album_id: a11.id)
Track.create(name: "Black Dog", duration: "4:55", album_id: a11.id)
Track.create(name: "Rock And Roll", duration: "3:40", album_id: a11.id)
Track.create(name: "The Battle Of Evermore", duration: "5:52", album_id: a11.id)
Track.create(name: "When The Levee Breaks", duration: "7:10", album_id: a11.id)
Track.create(name: "Stairway To Heaven", duration: "8:02", album_id: a11.id)
Track.create(name: "The Song Remains The Same", duration: "5:31", album_id: a11.id)
Track.create(name: "No Quarter", duration: "7:00", album_id: a11.id)
Track.create(name: "Houses Of The Holy", duration: "4:03", album_id: a11.id)
Track.create(name: "Trampled Underfoot", duration: "5:36", album_id: a11.id)
Track.create(name: "Kashmir", duration: "8:29", album_id: a11.id)
Track.create(name: "Ten Years Gone", duration: "6:32", album_id: a11.id)
Track.create(name: "Achilles Last Stand", duration: "10:22", album_id: a11.id)
Track.create(name: "Nobody's Fault But Mine", duration: "6:18", album_id: a11.id)
Track.create(name: "All My Love", duration: "5:52", album_id: a11.id)
Track.create(name: "In The Evening", duration: "6:51", album_id: a11.id)

a12 = Album.create(title: "Spirit", artist: "Leona Lewis", year: "2008", cd_number: 1, genre: "RnB/Swing, Ballad", tracks_num: 13, label: "J Records, Syco Music, Sony BMG Music Entertainment", image: "https://myhaven.files.wordpress.com/2008/06/leona-lewis.jpg", listen: "https://www.youtube.com/watch?v=zMvBlG2qgXM&list=PLDBF989160833074E")
Track.create(name: "Bleeding Love", duration: "4:23", album_id: a12.id)
Track.create(name: "Better In Time", duration: "3:55", album_id: a12.id)
Track.create(name: "I Will Be", duration: "4:00", album_id: a12.id)
Track.create(name: "I'm You", duration: "3:48", album_id: a12.id)
Track.create(name: "Forgive Me", duration: "3:41", album_id: a12.id)
Track.create(name: "Misses Glass", duration: "3:41", album_id: a12.id)
Track.create(name: "Angel", duration: "4:15", album_id: a12.id)
Track.create(name: "The First Time Ever I Saw Your Face", duration: "4:27", album_id: a12.id)
Track.create(name: "Yesterday", duration: "3:55", album_id: a12.id)
Track.create(name: "Whatever It Takes", duration: "3:27", album_id: a12.id)
Track.create(name: "Take A Bow", duration: "3:54", album_id: a12.id)
Track.create(name: "Footprints In The Sand", duration: "4:09", album_id: a12.id)
Track.create(name: "Here I Am", duration: "4:50", album_id: a12.id)

a13 = Album.create(title: "Hybrid Theory", artist: "Linkin Park", year: "2000", cd_number: 1, genre: "Nu Metal", tracks_num: 12, label: "Warner Bros. Records", image: "http://cdn.discogs.com/E4LKVAODoaQxd8tTnXF61B-_mYk=/fit-in/350x350/filters:strip_icc():format(jpeg):mode_rgb():quality(96)/discogs-images/R-4484533-1366207747-6232.jpeg.jpg", listen: "https://www.youtube.com/watch?v=9tm8lueDbE8")
Track.create(name: "Papercut", duration: "3:05", album_id: a13.id)
Track.create(name: "One Step Closer", duration: "2:36", album_id: a13.id)
Track.create(name: "With You", duration: "3:23", album_id: a13.id)
Track.create(name: "Points Of Authority", duration: "3:20", album_id: a13.id)
Track.create(name: "Crawling", duration: "3:29", album_id: a13.id)
Track.create(name: "Runaway", duration: "3:04", album_id: a13.id)
Track.create(name: "By Myself", duration: "3:10", album_id: a13.id)
Track.create(name: "In The End", duration: "3:36", album_id: a13.id)
Track.create(name: "A Place For My Head", duration: "3:05", album_id: a13.id)
Track.create(name: "Forgotten", duration: "3:14", album_id: a13.id)
Track.create(name: "Cure For The Itch", duration: "2:37", album_id: a13.id)
Track.create(name: "Pushing Me Away", duration: "3:12", album_id: a13.id)

a14 = Album.create(title: "Reanimation", artist: "Linkin Park", year: "2002", cd_number: 1, genre: "Breakbeat, Hip Hop, Nu Metal", tracks_num: 20, label: "Warner Bros. Records", image: "http://images.sodahead.com/polls/000080535/polls_Reanimation_1655_906752_poll_xlarge.jpeg", listen: "https://www.youtube.com/watch?v=1LX9XXRwFyM")
Track.create(name: "Opening", duration: "1:07", album_id: a14.id)
Track.create(name: "Pts.Of.Athrty", duration: "3:45", album_id: a14.id)
Track.create(name: "Enth E Nd", duration: "3:59", album_id: a14.id)
Track.create(name: "[Chali]", duration: "0:23", album_id: a14.id)
Track.create(name: "Frgt/10", duration: "3:32", album_id: a14.id)
Track.create(name: "P5hng Me A*wy", duration: "4:37", album_id: a14.id)
Track.create(name: "Plc.4 Mie Hæd", duration: "4:20", album_id: a14.id)
Track.create(name: "X-Ecutioner Style", duration: "1:49", album_id: a14.id)
Track.create(name: "H! Vltg3", duration: "3:30", album_id: a14.id)
Track.create(name: "[Riff Raff]", duration: "0:21", album_id: a14.id)
Track.create(name: "Wth&gt;You", duration: "4:12", album_id: a14.id)
Track.create(name: "Ntr\\Mssion", duration: "0:29", album_id: a14.id)
Track.create(name: "Ppr:Kut", duration: "3:26", album_id: a14.id)
Track.create(name: "Rnw@y", duration: "3:13", album_id: a14.id)
Track.create(name: "My&lt;Dsmbr", duration: "4:17", album_id: a14.id)
Track.create(name: "[Stef]", duration: "0:10", album_id: a14.id)
Track.create(name: "By_Myslf", duration: "3:42", album_id: a14.id)
Track.create(name: "Kyur4 Th Ich", duration: "2:32", album_id: a14.id)
Track.create(name: "1stp Klosr", duration: "5:46", album_id: a14.id)
Track.create(name: "Krwlng", duration: "5:40", album_id: a14.id)

a15 = Album.create(title: "Meteora", artist: "Linkin Park", year: "2003", cd_number: 1, genre: "Nu Metal", tracks_num: 14, label: "Warner Bros. Records", image: "https://artwork-cdn.7static.com/static/img/sleeveart/00/000/421/0000042194_350.jpg", listen: "https://www.youtube.com/watch?v=_vZ7sS4n7oU")
Track.create(name: "Foreword", duration: "0:13", album_id: a15.id)
Track.create(name: "Don't Stay", duration: "3:08", album_id: a15.id)
Track.create(name: "Somewhere I Belong", duration: "3:34", album_id: a15.id)
Track.create(name: "Lying From You", duration: "2:55", album_id: a15.id)
Track.create(name: "Hit The Floor", duration: "2:44", album_id: a15.id)
Track.create(name: "Easier To Run", duration: "3:24", album_id: a15.id)
Track.create(name: "Faint", duration: "2:42", album_id: a15.id)
Track.create(name: "Figure.09", duration: "3:17", album_id: a15.id)
Track.create(name: "Breaking The Habit", duration: "3:16", album_id: a15.id)
Track.create(name: "From The Inside", duration: "2:55", album_id: a15.id)
Track.create(name: "Nobody's Listening", duration: "2:58", album_id: a15.id)
Track.create(name: "Session", duration: "2:24", album_id: a15.id)
Track.create(name: "Numb", duration: "3:07", album_id: a15.id)
Track.create(name: "Video - The Art Of Meteora", duration: "17:04", album_id: a15.id)

a16 = Album.create(title: "Minutes To Midnight", artist: "Linkin Park", year: "2007", cd_number: 1, genre: "Alternative Rock", tracks_num: 12, label: "Warner Bros. Records", image: "https://artwork-cdn.7static.com/static/img/sleeveart/00/002/427/0000242716_350.jpg", listen: "https://www.youtube.com/watch?v=3mPmHBsjlcI")
Track.create(name: "Wake", duration: "1:40", album_id: a16.id)
Track.create(name: "Given Up", duration: "3:09", album_id: a16.id)
Track.create(name: "Leave Out All The Rest", duration: "3:29", album_id: a16.id)
Track.create(name: "Bleed It Out", duration: "2:44", album_id: a16.id)
Track.create(name: "Shadow Of The Day", duration: "4:49", album_id: a16.id)
Track.create(name: "What I've Done", duration: "3:25", album_id: a16.id)
Track.create(name: "Hands Held High", duration: "3:53", album_id: a16.id)
Track.create(name: "No More Sorrow", duration: "3:41", album_id: a16.id)
Track.create(name: "Valentine's Day", duration: "3:16", album_id: a16.id)
Track.create(name: "In Between", duration: "3:16", album_id: a16.id)
Track.create(name: "In Pieces", duration: "3:38", album_id: a16.id)
Track.create(name: "The Little Things Give You Away", duration: "6:23", album_id: a16.id)

a17 = Album.create(title: "A Thousand Suns", artist: "Linkin Park", year: "2011", cd_number: 2, genre: "Alternative Rock", tracks_num: 34, label: "Warner Bros. Records", image: "http://eil.com/images/main/Linkin-Park-A-Thousand-Suns-539519.jpg", listen: "https://www.youtube.com/watch?v=96gzqFTvWtk")
Track.create(name: "A Thousand Suns", duration: " ", album_id: a17.id)
Track.create(name: "The Requiem", duration: "2:01", album_id: a17.id)
Track.create(name: "The Radiance", duration: "0:57", album_id: a17.id)
Track.create(name: "Burning In The Skies", duration: "4:13", album_id: a17.id)
Track.create(name: "Empty Spaces", duration: "0:18", album_id: a17.id)
Track.create(name: "When They Come For Me", duration: "4:55", album_id: a17.id)
Track.create(name: "Robot Boy", duration: "4:28", album_id: a17.id)
Track.create(name: "Jornada Del Muerto", duration: "1:34", album_id: a17.id)
Track.create(name: "Waiting For The End", duration: "3:51", album_id: a17.id)
Track.create(name: "Blackout", duration: "4:39", album_id: a17.id)
Track.create(name: "Wretches And Kings", duration: "4:15", album_id: a17.id)
Track.create(name: "Wisdom, Justice, And Love", duration: "1:38", album_id: a17.id)
Track.create(name: "Iridescent", duration: "4:56", album_id: a17.id)
Track.create(name: "Fallout", duration: "1:23", album_id: a17.id)
Track.create(name: "The Catalyst", duration: "5:39", album_id: a17.id)
Track.create(name: "The Messenger", duration: "3:01", album_id: a17.id)
Track.create(name: "Live From Madrid - The Requiem", duration: "2:07", album_id: a17.id)
Track.create(name: "Live From Madrid - Wretches And Kings", duration: "3:54", album_id: a17.id)
Track.create(name: "Live From Madrid - Papercut", duration: "3:26", album_id: a17.id)
Track.create(name: "Live From Madrid - New Divide", duration: "4:22", album_id: a17.id)
Track.create(name: "Live From Madrid - Faint", duration: "4:14", album_id: a17.id)
Track.create(name: "Live From Madrid - Empty Spaces/When They Come For Me", duration: "5:22", album_id: a17.id)
Track.create(name: "Live From Madrid - Waiting For The End", duration: "3:52", album_id: a17.id)
Track.create(name: "Live From Madrid - Iridescent", duration: "5:01", album_id: a17.id)
Track.create(name: "Live From Madrid - Numb", duration: "3:10", album_id: a17.id)
Track.create(name: "Live From Madrid - The Radiance", duration: "1:48", album_id: a17.id)
Track.create(name: "Live From Madrid - Breaking The Habit", duration: "3:58", album_id: a17.id)
Track.create(name: "Live From Madrid - Shadow Of The Day", duration: "5:13", album_id: a17.id)
Track.create(name: "Live From Madrid - Fallout", duration: "1:24", album_id: a17.id)
Track.create(name: "Live From Madrid - The Catalyst", duration: "6:11", album_id: a17.id)
Track.create(name: "Live From Madrid - The Messenger", duration: "3:39", album_id: a17.id)
Track.create(name: "Live From Madrid - In The End", duration: "3:30", album_id: a17.id)
Track.create(name: "Live From Madrid - What I've Done", duration: "3:31", album_id: a17.id)
Track.create(name: "Live From Madrid - Bleed It Out/A Place For My Head", duration: "5:04", album_id: a17.id)

a18 = Album.create(title: "Living Things", artist: "Linkin Park", year: "2012", cd_number: 1, genre: "Alternative Rock", tracks_num: 12, label: "Warner Bros. Records", image: "http://ourzonemag.com/oz/wp-content/uploads/2012/04/livingThings.jpg", listen: "https://www.youtube.com/watch?v=EK3BKgYAhIU")
Track.create(name: "Lost In The Echo", duration: "3:25", album_id: a18.id)
Track.create(name: "In My Remains", duration: "3:21", album_id: a18.id)
Track.create(name: "Burn It Down", duration: "3:52", album_id: a18.id)
Track.create(name: "Lies Greed Misery", duration: "2:27", album_id: a18.id)
Track.create(name: "I'll Be Gone", duration: "3:31", album_id: a18.id)
Track.create(name: "Castle Of Glass", duration: "3:25", album_id: a18.id)
Track.create(name: "Victimized", duration: "1:47", album_id: a18.id)
Track.create(name: "Roads Untraveled", duration: "3:50", album_id: a18.id)
Track.create(name: "Skin To Bone", duration: "2:49", album_id: a18.id)
Track.create(name: "Until It Breaks", duration: "3:44", album_id: a18.id)
Track.create(name: "Tinfoil", duration: "1:12", album_id: a18.id)
Track.create(name: "Powerless", duration: "3:44", album_id: a18.id)

a19 = Album.create(title: "The Hunting Party", artist: "Linkin Park", year: "2014", cd_number: 1, genre: "Hard Rock, Alternative Rock", tracks_num: 12, label: "Warner Bros. Records", image: "http://wizard.bg/media/img7/S_LinkinPark_TheHunting.jpg", listen: "https://www.youtube.com/watch?v=-0v-gFBk1z0")
Track.create(name: "Keys To The Kingdom", duration: "3:38", album_id: a19.id)
Track.create(name: "All For Nothing", duration: "3:33", album_id: a19.id)
Track.create(name: "Guilty All The Same", duration: "5:56", album_id: a19.id)
Track.create(name: "The Summoning", duration: "1:00", album_id: a19.id)
Track.create(name: "War", duration: "2:11", album_id: a19.id)
Track.create(name: "Wastelands", duration: "3:15", album_id: a19.id)
Track.create(name: "Until It's Gone", duration: "3:53", album_id: a19.id)
Track.create(name: "Rebellion", duration: "3:44", album_id: a19.id)
Track.create(name: "Mark The Graves", duration: "5:05", album_id: a19.id)
Track.create(name: "Drawbar", duration: "2:46", album_id: a19.id)
Track.create(name: "Final Masquerade", duration: "3:37", album_id: a19.id)
Track.create(name: "A Line In The Sand", duration: "6:35", album_id: a19.id)

a20 = Album.create(title: "Mezzanine", artist: "Massive Attack", year: "1998", cd_number: 1, genre: "Leftfield, Trip Hop, Downtempo", tracks_num: 11, label: "Virgin", image: "http://ecx.images-amazon.com/images/I/41V8JTFM7WL.jpg", listen: "https://www.youtube.com/watch?v=6-pfLbrbb2Q")
Track.create(name: "Angel", duration: "6:18", album_id: a20.id)
Track.create(name: "Risingson", duration: "4:58", album_id: a20.id)
Track.create(name: "Teardrop", duration: "5:29", album_id: a20.id)
Track.create(name: "Inertia Creeps", duration: "5:56", album_id: a20.id)
Track.create(name: "Exchange", duration: "4:11", album_id: a20.id)
Track.create(name: "Dissolved Girl", duration: "6:07", album_id: a20.id)
Track.create(name: "Man Next Door", duration: "5:55", album_id: a20.id)
Track.create(name: "Black Milk", duration: "6:20", album_id: a20.id)
Track.create(name: "Mezzanine", duration: "5:54", album_id: a20.id)
Track.create(name: "Group Four", duration: "8:13", album_id: a20.id)
Track.create(name: "(Exchange)", duration: "4:08", album_id: a20.id)

a21 = Album.create(title: "Hold Your Colour", artist: "Pendulum", year: "2005", cd_number: 1, genre: "Breaks, Drum n Bass", tracks_num: 14, label: "Breakbeat Kaos", image: "http://www.redeyerecords.co.uk/imagery/cat7106-1.jpg", listen: "https://www.youtube.com/watch?v=uv1XG1A9dUU")
Track.create(name: "Prelude", duration: "0:53", album_id: a21.id)
Track.create(name: "Slam", duration: "5:45", album_id: a21.id)
Track.create(name: "Plasticworld", duration: "6:22", album_id: a21.id)
Track.create(name: "Fasten Your Seatbelt", duration: "6:38", album_id: a21.id)
Track.create(name: "Through The Loop", duration: "6:14", album_id: a21.id)
Track.create(name: "Sounds Of Life", duration: "5:21", album_id: a21.id)
Track.create(name: "Girl In The Fire", duration: "4:54", album_id: a21.id)
Track.create(name: "Tarantula", duration: "5:31", album_id: a21.id)
Track.create(name: "Out Here", duration: "6:07", album_id: a21.id)
Track.create(name: "Hold Your Colour", duration: "5:29", album_id: a21.id)
Track.create(name: "The Terminal", duration: "5:42", album_id: a21.id)
Track.create(name: "Streamline", duration: "5:24", album_id: a21.id)
Track.create(name: "Another Planet", duration: "7:38", album_id: a21.id)
Track.create(name: "Still Grey", duration: "7:52", album_id: a21.id)

a22 = Album.create(title: "The Dark Side Of The Moon", artist: "Pink Floyd", year: "1973", cd_number: 1, genre: "Psychedelic Rock, Prog Rock", tracks_num: 10, label: "EMI Records Ltd.", image: "http://www.inthestudio.net/wp-content/uploads/2013/03/isbel1.jpg", listen: "https://www.youtube.com/watch?v=6tYu_LaNx9E")
Track.create(name: "Speak To Me", duration: "1:10", album_id: a22.id)
Track.create(name: "Breathe In The Air", duration: "2:47", album_id: a22.id)
Track.create(name: "On The Run", duration: "3:31", album_id: a22.id)
Track.create(name: "Time", duration: "7:05", album_id: a22.id)
Track.create(name: "The Great Gig In The Sky", duration: "4:47", album_id: a22.id)
Track.create(name: "Money", duration: "6:23", album_id: a22.id)
Track.create(name: "Us And Them", duration: "7:48", album_id: a22.id)
Track.create(name: "Any Colour You Like", duration: "3:25", album_id: a22.id)
Track.create(name: "Brain Damage", duration: "3:50", album_id: a22.id)
Track.create(name: "Eclipse", duration: "2:06", album_id: a22.id)

a23 = Album.create(title: "Greatest Hits", artist: "Queen", year: "1986", cd_number: 1, genre: "Pop Rock, Hard Rock", tracks_num: 17, label: "EMI Records Ltd.", image: "http://www.10mag.com/wp-content/uploads/2011/03/music-queen.jpg", listen: "https://www.youtube.com/watch?v=fKSvE7ZRsbk&list=PL2xwq6jogRe2IhSH0VoJNeCqVYhWrngpe")
Track.create(name: "Bohemian Rhapsody", duration: "5:52", album_id: a23.id)
Track.create(name: "Another One Bites The Dust", duration: "3:32", album_id: a23.id)
Track.create(name: "Killer Queen", duration: "2:59", album_id: a23.id)
Track.create(name: "Fat Bottomed Girls", duration: "3:21", album_id: a23.id)
Track.create(name: "Bicycle Race", duration: "2:59", album_id: a23.id)
Track.create(name: "You're My Best Friend", duration: "2:50", album_id: a23.id)
Track.create(name: "Don't Stop Me Now", duration: "3:29", album_id: a23.id)
Track.create(name: "Save Me", duration: "3:48", album_id: a23.id)
Track.create(name: "Crazy Little Thing Called Love", duration: "2:41", album_id: a23.id)
Track.create(name: "Somebody To Love", duration: "4:53", album_id: a23.id)
Track.create(name: "Now I'm Here", duration: "4:12", album_id: a23.id)
Track.create(name: "Good Old-Fashioned Lover Boy", duration: "2:53", album_id: a23.id)
Track.create(name: "Play The Game", duration: "3:28", album_id: a23.id)
Track.create(name: "Flash", duration: "2:16", album_id: a23.id)
Track.create(name: "Seven Seas Of Rhye", duration: "2:47", album_id: a23.id)
Track.create(name: "We Will Rock You", duration: "2:00", album_id: a23.id)
Track.create(name: "We Are The Champions", duration: "3:00", album_id: a23.id)

a24 = Album.create(title: "Greatest Hits II", artist: "Queen", year: "1991", cd_number: 1, genre: "Pop Rock, Hard Rock", tracks_num: 17, label: "Parlophone", image: "http://lyricsmusic.name/img/photos/aqueen-greatest-hits-ii.jpg", listen: "https://www.youtube.com/watch?v=hS__M1Fa418&list=PL2xwq6jogRe1yu0_RHmxxT3vlo4VZEjq1")
Track.create(name: "A Kind Of Magic", duration: "4:20", album_id: a24.id)
Track.create(name: "Under Pressure", duration: "3:54", album_id: a24.id)
Track.create(name: "Radio Ga Ga", duration: "5:41", album_id: a24.id)
Track.create(name: "I Want It All", duration: "3:59", album_id: a24.id)
Track.create(name: "I Want To Break Free", duration: "4:16", album_id: a24.id)
Track.create(name: "Innuendo", duration: "6:25", album_id: a24.id)
Track.create(name: "It's A Hard Life", duration: "4:07", album_id: a24.id)
Track.create(name: "Breakthru", duration: "4:07", album_id: a24.id)
Track.create(name: "Who Wants To Live Forever", duration: "4:55", album_id: a24.id)
Track.create(name: "Headlong", duration: "4:31", album_id: a24.id)
Track.create(name: "The Miracle", duration: "4:52", album_id: a24.id)
Track.create(name: "I'm Going Slightly Mad", duration: "4:05", album_id: a24.id)
Track.create(name: "The Invisible Man", duration: "3:56", album_id: a24.id)
Track.create(name: "Hammer To Fall", duration: "3:38", album_id: a24.id)
Track.create(name: "Friends Will Be Friends", duration: "4:06", album_id: a24.id)
Track.create(name: "The Show Must Go On", duration: "4:21", album_id: a24.id)
Track.create(name: "One Vision", duration: "4:02", album_id: a24.id)

a25 = Album.create(title: "Supernatural", artist: "Santana", year: "1999", cd_number: 1, genre: "Blues Rock, Classic Rock", tracks_num: 13, label: "Arista Records, Inc.", image: "http://www.musica.co.za/images/made/8ae1a39bc38a541a/6007124307033_350_350_80_int_s_c1.jpg", listen: "https://www.youtube.com/watch?v=VYEgCukYZbA&list=PL-UWPlRIl68pCXAReoEp1ti75dqKJ4eRj")
Track.create(name: "(Da Le) Yaleo", duration: "5:51", album_id: a25.id)
Track.create(name: "Love Of My Life", duration: "5:48", album_id: a25.id)
Track.create(name: "Put Your Lights On", duration: "4:47", album_id: a25.id)
Track.create(name: "Africa Bamba", duration: "4:40", album_id: a25.id)
Track.create(name: "Smooth", duration: "4:56", album_id: a25.id)
Track.create(name: "Do You Like The Way", duration: "5:52", album_id: a25.id)
Track.create(name: "Maria Maria", duration: "4:21", album_id: a25.id)
Track.create(name: "Migra", duration: "5:24", album_id: a25.id)
Track.create(name: "Corazon Espinado", duration: "4:32", album_id: a25.id)
Track.create(name: "Wishing It Was", duration: "4:59", album_id: a25.id)
Track.create(name: "El Farol", duration: "4:49", album_id: a25.id)
Track.create(name: "Primavera", duration: "5:17", album_id: a25.id)
Track.create(name: "The Calling", duration: "7:48", album_id: a25.id)

a26 = Album.create(title: "Shaman", artist: "Santana", year: "2002", cd_number: 1, genre: "Blues Rock, Classic Rock", tracks_num: 16, label: "Arista Records, Inc.", image: "http://flacmusic.net/uploads/posts/2011-09/1315146441_s.jpg", listen: "https://www.youtube.com/watch?v=pl1RulK8TYw&list=PLD5C5FFC2447DDB51")
Track.create(name: "Adouma", duration: "4:15", album_id: a26.id)
Track.create(name: "Nothing At All", duration: "4:28", album_id: a26.id)
Track.create(name: "The Game Of Love", duration: "4:14", album_id: a26.id)
Track.create(name: "You Are My Kind", duration: "4:19", album_id: a26.id)
Track.create(name: "Amoré (Sexo)", duration: "3:51", album_id: a26.id)
Track.create(name: "Foo Foo", duration: "6:28", album_id: a26.id)
Track.create(name: "Victory Is Won", duration: "5:20", album_id: a26.id)
Track.create(name: "America", duration: "4:35", album_id: a26.id)
Track.create(name: "Sideways", duration: "4:41", album_id: a26.id)
Track.create(name: "Why Don't You &amp; I", duration: "4:34", album_id: a26.id)
Track.create(name: "Feels Like Fire", duration: "4:39", album_id: a26.id)
Track.create(name: "Let Me Love You Tonight", duration: "5:34", album_id: a26.id)
Track.create(name: "Aye Aye Aye", duration: "4:45", album_id: a26.id)
Track.create(name: "Hoy Es Adios", duration: "4:37", album_id: a26.id)
Track.create(name: "One Of These Days", duration: "5:51", album_id: a26.id)
Track.create(name: "Novus", duration: "4:12", album_id: a26.id)

a27 = Album.create(title: "All That I Am", artist: "Santana", year: "2005", cd_number: 1, genre: "Blues Rock, Classic Rock", tracks_num: 13, label: "Arista Records, Inc.", image: "https://artwork-cdn.7static.com/static/img/sleeveart/00/005/147/0000514725_350.jpg", listen: "https://www.youtube.com/watch?v=FtBp5gOv8T8&list=PL1T0hHFDjgDGnuYGg_htELjSZKjt5r10i")
Track.create(name: "Hermes", duration: "4:08", album_id: a27.id)
Track.create(name: "El Fuego", duration: "4:17", album_id: a27.id)
Track.create(name: "I'm Feeling You", duration: "4:30", album_id: a27.id)
Track.create(name: "My Man", duration: "4:37", album_id: a27.id)
Track.create(name: "Just Feel Better", duration: "4:12", album_id: a27.id)
Track.create(name: "I Am Somebody", duration: "4:02", album_id: a27.id)
Track.create(name: "Con Santana", duration: "3:18", album_id: a27.id)
Track.create(name: "Twisted", duration: "5:11", album_id: a27.id)
Track.create(name: "Trinity", duration: "3:35", album_id: a27.id)
Track.create(name: "Cry Baby Cry", duration: "3:53", album_id: a27.id)
Track.create(name: "Brown Skin Girl", duration: "4:44", album_id: a27.id)
Track.create(name: "I Don't Wanna Lose Your Love", duration: "4:00", album_id: a27.id)
Track.create(name: "Da Tu Amor", duration: "6:35", album_id: a27.id)

a28 = Album.create(title: "Guitar Heaven: The Greatest Guitar Classics Of All Time", artist: "Santana", year: "2010", cd_number: 1, genre: "Hard Rock", tracks_num: 13, label: "Arista Records, Inc.", image: "http://itunesm4a.net/wp-content/uploads/2014/01/mzi.orahmzdf.600x600-75-350x350.jpg", listen: "https://www.youtube.com/watch?v=dF_Te3rcB4g&list=PLTjq2zlQ60ZQqhhxEy_qNaVgCm_hKppKP")
Track.create(name: "Whole Lotta Love", duration: "3:51", album_id: a28.id)
Track.create(name: "Can't You Hear Me Knocking ", duration: "5:38", album_id: a28.id)
Track.create(name: "Sunshine Of Your Love", duration: "4:43", album_id: a28.id)
Track.create(name: "While My Guitar Gently Weeps ", duration: "6:02", album_id: a28.id)
Track.create(name: "Photograph ", duration: "4:03", album_id: a28.id)
Track.create(name: "Back In Black ", duration: "4:20", album_id: a28.id)
Track.create(name: "Riders On The Storm ", duration: "5:23", album_id: a28.id)
Track.create(name: "Smoke On The Water ", duration: "5:06", album_id: a28.id)
Track.create(name: "Dance The Night Away ", duration: "3:23", album_id: a28.id)
Track.create(name: "Bang A Gong ", duration: "3:41", album_id: a28.id)
Track.create(name: "Little Wing ", duration: "4:52", album_id: a28.id)
Track.create(name: "I Ain't Superstitious ", duration: "3:57", album_id: a28.id)
Track.create(name: "Under The Bridge", duration: "5:09", album_id: a28.id)

a29 = Album.create(title: "Conspiracy Of One", artist: "The Offspring", year: "2000", cd_number: 1, genre: "Alternative Rock, Punk, Pop Rock", tracks_num: 13, label: "Columbia", image: "https://artwork-cdn.7static.com/static/img/sleeveart/00/005/494/0000549492_350.jpg", listen: "https://www.youtube.com/watch?v=o6ccuDbrNZw")
Track.create(name: "Intro", duration: "0:05", album_id: a29.id)
Track.create(name: "Come Out Swinging", duration: "2:47", album_id: a29.id)
Track.create(name: "Original Prankster", duration: "3:40", album_id: a29.id)
Track.create(name: "Want You Bad", duration: "3:22", album_id: a29.id)
Track.create(name: "Million Miles Away", duration: "3:39", album_id: a29.id)
Track.create(name: "Dammit, I Changed Again", duration: "2:48", album_id: a29.id)
Track.create(name: "Living In Chaos", duration: "3:28", album_id: a29.id)
Track.create(name: "Special Delivery", duration: "3:00", album_id: a29.id)
Track.create(name: "One Fine Day", duration: "2:44", album_id: a29.id)
Track.create(name: "All Along", duration: "1:38", album_id: a29.id)
Track.create(name: "Denial, Revisited", duration: "4:32", album_id: a29.id)
Track.create(name: "Vultures", duration: "3:34", album_id: a29.id)
Track.create(name: "Conspiracy Of One", duration: "2:17", album_id: a29.id)

a30 = Album.create(title: "Music For The Jilted Generation", artist: "The Prodigy", year: "1994", cd_number: 1, genre: "Breakbeat, Techno, Big Beat", tracks_num: 13, label: "XL Recordings", image: "https://upload.wikimedia.org/wikipedia/en/8/86/TheProdigy-MusicForTheJiltedGeneration.jpg", listen: "https://www.youtube.com/watch?v=8oUgShnuiH0&list=PLcHYbQDWGZw3Ms4OfzYv0ynaZkr5L_ajS ")
Track.create(name: "Intro", duration: "0:46", album_id: a30.id)
Track.create(name: "Break &amp; Enter", duration: "8:24", album_id: a30.id)
Track.create(name: "Their Law", duration: "6:41", album_id: a30.id)
Track.create(name: "Full Throttle", duration: "5:03", album_id: a30.id)
Track.create(name: "Voodoo People", duration: "6:27", album_id: a30.id)
Track.create(name: "Speedway (Theme From Fastlane)", duration: "8:56", album_id: a30.id)
Track.create(name: "The Heat (The Energy)", duration: "4:28", album_id: a30.id)
Track.create(name: "Poison", duration: "6:42", album_id: a30.id)
Track.create(name: "No Good (Start The Dance)", duration: "6:18", album_id: a30.id)
Track.create(name: "One Love (Edit)", duration: "3:53", album_id: a30.id)
Track.create(name: "3 Kilos", duration: "7:26", album_id: a30.id)
Track.create(name: "Skylined", duration: "5:58", album_id: a30.id)
Track.create(name: "Claustrophobic Sting", duration: "7:12", album_id: a30.id)
